AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Centralized logging for API Gateway events using CloudWatch Logs.
  This stack sets up a CloudWatch Log Group, an IAM Role for API Gateway logging,
  and configures the API Gateway account to use that role.

Resources:
  # CloudWatch Log Group for API Gateway events
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/apigateway/events"
      RetentionInDays: 30

  # IAM Role for API Gateway to write logs to CloudWatch Logs
  ApiGatewayLogsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "ApiGatewayLogsRoleForLogging"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ApiGatewayLoggingPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  # Configure the API Gateway account to use the CloudWatch Logs role
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayLogsRole.Arn

Outputs:
  LogGroupName:
    Description: "CloudWatch Logs Log Group for API Gateway events"
    Value: !Ref ApiGatewayLogGroup
  ApiGatewayLogsRoleArn:
    Description: "IAM Role ARN used by API Gateway for logging"
    Value: !GetAtt ApiGatewayLogsRole.Arn
