AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Centralized logging for API Gateway events using CloudWatch Logs.
  This stack sets up an IAM role with the required trust and permissions and then assigns
  it to API Gateway via the AWS::ApiGateway::Account resource.

Resources:
  # CloudWatch Log Group for API Gateway logs (optional if you want to create one explicitly)
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/apigateway/events"
      RetentionInDays: 30

  # IAM Role for API Gateway logging
  ApiGatewayLogsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "ApiGatewayLogsRoleForLogging"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ApiGatewayLoggingPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "AllowAPIGatewayLogging"
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  # Set the CloudWatch Logs role at the API Gateway account level.
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayLogsRole.Arn

Outputs:
  ApiGatewayLogsRoleArn:
    Description: "The ARN of the IAM Role for API Gateway Logging"
    Value: !GetAtt ApiGatewayLogsRole.Arn
