AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Base API Gateway REST API template.
  Defines common resources (custom authorizer, optional /html resource, etc.).

Parameters:
  ApiName:
    Type: String
    Description: The name of the API Gateway API.
  LambdaFunctionArn:
    Type: String
    Description: ARN of the Lambda function for the integration.
  HtmlEndpoint:
    Type: String
    Description: URL for the /html integration. Leave empty if not used.
    Default: ""
  StageName:
    Type: String
    Description: Deployment stage (e.g., dev, prod).
  AuthorizerLambdaArn:
    Type: String
    Description: ARN of the Lambda function for the custom authorizer (base ARN only).
  LambdaDevAlias:
    Type: String
    Description: Lambda alias to use in the Dev stage.
  LambdaProdAlias:
    Type: String
    Description: Lambda alias to use in the Prod stage.

Conditions:
  CreateHtmlResource: !Not [!Equals [!Ref HtmlEndpoint, ""]]

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiName
      Description: "API Gateway managed via CloudFormation and GitHub Actions"

  CustomAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: "MyLambdaAuthorizer"
      Type: TOKEN
      RestApiId: !Ref RestApi
      IdentitySource: method.request.header.Authorization
      AuthorizerUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerLambdaArn}/invocations"
      AuthorizerResultTtlInSeconds: 300

  HtmlResource:
    Type: AWS::ApiGateway::Resource
    Condition: CreateHtmlResource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: html
      RestApiId: !Ref RestApi

  HtmlMethod:
    Type: AWS::ApiGateway::Method
    Condition: CreateHtmlResource
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref HtmlResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: GET
        Type: HTTP
        Uri: !Ref HtmlEndpoint
      MethodResponses:
        - StatusCode: 200

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CustomAuthorizer
    Properties:
      RestApiId: !Ref RestApi

  DevStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: dev
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      Variables:
        lambdaAlias: !Ref LambdaDevAlias

  ProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      Variables:
        lambdaAlias: !Ref LambdaProdAlias

Outputs:
  ApiUrlDev:
    Description: "Dev API URL"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
  ApiUrlProd:
    Description: "Prod API URL"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
