name: Approve and Deploy API Gateway To Prod

on:
  workflow_dispatch:
    inputs:
      east-resourceId:
        description: "API Resource ID"
        required: true
        type: string
      west-resourceId:
        description: "API Resource ID"
        required: true
        type: string

jobs:
  manual_approval:
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Request Manual Approval
        run: |
          echo "Waiting for manual approval to deploy API Gateway."

  deploy_apigateway:
    needs: manual_approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy API to Prod
        run: |
          aws apigateway create-deployment --rest-api-id "${{ github.event.inputs.east-resourceId }}" --stage-name prod --description 'Deployed from CLI'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy API to Prod
        run: |
          aws apigateway create-deployment --rest-api-id "${{ github.event.inputs.west-resourceId }}" --stage-name prod --description 'Deployed from CLI'
