name: Deploy APIs with Multi-Stage

on:
  push:
    branches: nazir
    paths:
      - "src/cloudFormationTemplates/*.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine changed CF templates
        id: cffiles
        run: |
          echo "Finding changed CloudFormation templates in cfTemplates/ folder..."
          # Use git diff to get changed files between the previous commit and current commit
          changed_files=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" | grep '^cfTemplates/.*\.yaml$' || true)
          echo "Changed files: $changed_files"
          # Set output; note that if there are no changes, changed_files will be empty.
          echo "::set-output name=files::$changed_files"

      - name: Deploy Changed CF Templates
        if: steps.detect.outputs.files != ''
        run: |
          files="${{ steps.cffiles.outputs.files }}"
          echo "Deploying the following CloudFormation templates:"
          echo "$files"
          for file in $files; do
            # Construct a stack name from the template file name (without extension)
            stackName=$(basename "$file" .yaml)
            echo "Deploying template: $file to stack: $stackName"
            aws cloudformation deploy \
              --stack-name "$stackName" \
              --template-file "$file" \
              --capabilities CAPABILITY_NAMED_IAM \
              --region us-east-1
          done

      - name: No CF Templates Changed
        if: steps.cffiles.outputs.files == ''
        run: echo "No CloudFormation template changes detected. Skipping deployment."
