name: Deploy APIs with Multi-Stage

on:
  push:
    branches: nazir
    paths:
      - "iac/params/apis.json"
      - "iac/params/dynamic_paths.json"
      - "iac/cloudformation-api.base.yaml"
      - "iac/generate_resources.py"
      - "src/**"
  workflow_dispatch:

jobs:
  set-matrix:
    name: Set Matrix from JSON Parameters
    runs-on: ubuntu-latest
    outputs:
      api_matrix: ${{ steps.set_matrix.outputs.api_matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Read API Configurations from JSON
        id: set_matrix
        run: |
          MATRIX=$(jq -c '.apis' iac/params/apis.json)
          echo "api_matrix=$MATRIX" >> $GITHUB_OUTPUT

  deploy_api:
    name: Deploy API (Dev & Prod)
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api_config: ${{ fromJson(needs.set-matrix.outputs.api_matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Update Lambda Code
        if: ${{ matrix.api_config.lambda_code_path != '' }}
        run: |
          echo "Packaging Lambda code for API: ${{ matrix.api_config.api_name }}"
          cd "${{ matrix.api_config.lambda_code_path }}"
          zip -r function.zip .
          # Extract the base ARN (remove any alias/version)
          BASE_FUNCTION_ARN=$(echo "${{ matrix.api_config.lambda_function_arn }}" | awk -F: '{OFS=":"; print $1,$2,$3,$4,$5,$6,$7}')
          echo "Updating Lambda function code for $BASE_FUNCTION_ARN"
          aws lambda update-function-code --function-name "$BASE_FUNCTION_ARN" --zip-file fileb://function.zip --region us-east-1
          cd -

      - name: Generate Dynamic Resources
        run: |
          python iac/generate_resources.py > iac/generated_resources.yaml

      - name: Merge Base Template with Dynamic Resources
        run: |
          # Install yq if not available
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          yq eval-all '. as $item ireduce ({}; . * $item )' iac/cloudformation-api.base.yaml iac/generated_resources.yaml > iac/cloudformation-api.yaml

      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body file://iac/cloudformation-api.yaml --region us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          echo "Deploying API: ${{ matrix.api_config.api_name }} with stack: ${{ matrix.api_config.stack_name }}"
          aws cloudformation deploy \
            --stack-name "${{ matrix.api_config.stack_name }}" \
            --template-file iac/cloudformation-api.yaml \
            --parameter-overrides ApiName=${{ matrix.api_config.api_name }} LambdaFunctionArn=${{ matrix.api_config.lambda_function_arn }} HtmlEndpoint=${{ matrix.api_config.html_endpoint }} AuthorizerLambdaArn=${{ matrix.api_config.authorizer_lambda_arn }} LambdaDevAlias=${{ matrix.api_config.lambda_dev_alias }} LambdaProdAlias=${{ matrix.api_config.lambda_prod_alias }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1

  prod_approval:
    name: Approve Prod Changes
    needs: deploy_api
    runs-on: ubuntu-latest
    environment:
      name: Production # Configure this environment in GitHub with required reviewers.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Manual Approval Step
        run: echo "Production deployment approved. The API stack has been deployed with both Dev and Prod stages."
